/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [require("./plugin")],
  daisytheming: {
    // darkTheme: {
    //   "primary": "#32fc86",
    //   "secondary": "#f49884",
    //   "accent": "#e8b7ff",
    //   "neutral": "#242031",
    //   "base-100": "#3f3041",
    //   "info": "#4eadda",
    //   "success": "#11835b",
    //   "warning": "#be9109",
    //   "error": "#e36759",
    // },
    themes: [
      {
        customTheme1: {
          "primary": "#057aff",
          "secondary": "#463aa1",
          "accent": "#c149ad",
          "neutral": "#021431",
          "base-100": "#ffffff",
          "info": "#93e6fb",
          "success": "#80ced1",
          "warning": "#efd8bd",
          "error": "#e58b8b",
        },
      },
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
  },
}
